services:
  - type: web
    name: fortigatex-server
    # env: node
    runtime: node
    plan: free # optional â€” can set to 'starter' or 'standard' if you want
    buildCommand: npm install
    startCommand: npm start
    # runtimeVersion: 20.11.1 # specify a full stable Node version
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

